from models.base import BaseModel


class User(BaseModel):
    attribute_mapper = {
        "username": "username",
        "password": "password",
        "enabled": "enableuser",
        "is_enabled": "enableuser",
        "account_type": "acctype",
        "service_id": "srvid",
        "simultaneous_use": "simuse",
        "use_mac_auth": "usemacauth",
        "mac": "maccpe",
        "cpe_mac_address": "maccpe",
        "cm_mac_address": "maccm",
        "group_id": "groupid",
        "custom_attributes": "custattr",
        "owner": "owner",
        "cm_static_ip": "staticipcm",
        "cpe_static_ip": "staticipcpe",
        "cm_ip_mode": "ipmodecm",
        "cpe_ip_mode": "ipmodecpe",
        "cm_ip_pool_id": "poolidcm",
        "cpe_ip_pool_id": "poolidcpe",
        "available_download_bytes": "dlbytes",
        "available_upload_bytes": "ulbytes",
        "available_total_bytes": "totalbytes",
        "expiry_date": "expiry",
        "available_online_time": "onlinetime",
        "balance": "credits",
        "contract_id": "contractid",
        "contract_valid_till": "contractvalid",
        "national_id": "cnic",
        "first_name": "firstname",
        "last_name": "lastname",
        "company_name": "company",
        "address": "address",
        "city": "city",
        "zip": "zip",
        "country": "country",
        "state": "state",
        "phone_number": "phone",
        "mobile_number": "mobile",
        "email": "email",
        "comment": "comment",
        "tax_id": "taxid",
        "gps_longitude": "gpslong",
        "gps_latitude": "gpslat",
        "language": "lang",
        "is_email_alerts_enabled": "alertemail",
        "is_sms_alerts_enabled": "alertsms",
        "is_warning_sent": "warningsent",
        "is_user_verified": "verified",
        "failed_verification_attempts": "verifyfails",
        "sent verification_codes_count": "verifysentnum",
        "send_password_codes_count": "pswactsmsnum"

    }

    def __init__(self, username=None, password=None, enabled=None, account_type=None, service_id=None,
                 simultaneous_use=None, use_mac_auth=None, mac=None, cm_mac_address=None, group_id=None,
                 custom_attributes=None, owner=None, cm_static_ip=None, cpe_static_ip=None, cm_ip_mode=None,
                 cpe_ip_mode=None, cm_ip_pool_id=None, cpe_ip_pool_id=None, available_download_bytes=None,
                 available_upload_bytes=None, available_total_bytes=None, expiry_date=None, available_online_time=None,
                 balance=None, contract_id=None, contract_valid_till=None, national_id=None, first_name=None,
                 last_name=None, company_name=None, address=None, city=None, zip=None, country=None, state=None,
                 phone_number=None, mobile_number=None, email=None, comment=None, tax_id=None, gps_longitude=None,
                 gps_latitude=None, language=None, **kwargs):
        cleaned_locals = self.remove_self_from_kwargs(**locals())
        super().__init__(**cleaned_locals)
